package com.lepetit.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lepetit.greendaohelper.ScheduleInfo;

import com.lepetit.dao.ScheduleInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scheduleInfoDaoConfig;

    private final ScheduleInfoDao scheduleInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scheduleInfoDaoConfig = daoConfigMap.get(ScheduleInfoDao.class).clone();
        scheduleInfoDaoConfig.initIdentityScope(type);

        scheduleInfoDao = new ScheduleInfoDao(scheduleInfoDaoConfig, this);

        registerDao(ScheduleInfo.class, scheduleInfoDao);
    }
    
    public void clear() {
        scheduleInfoDaoConfig.clearIdentityScope();
    }

    public ScheduleInfoDao getScheduleInfoDao() {
        return scheduleInfoDao;
    }

}
