package com.lepetit.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lepetit.greendaohelper.ExamInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXAM_INFO".
*/
public class ExamInfoDao extends AbstractDao<ExamInfo, Long> {

    public static final String TABLENAME = "EXAM_INFO";

    /**
     * Properties of entity ExamInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Course = new Property(1, String.class, "course", false, "Course");
        public final static Property Time = new Property(2, String.class, "time", false, "Time");
        public final static Property Classroom = new Property(3, String.class, "classroom", false, "Classroom");
        public final static Property Seat = new Property(4, String.class, "seat", false, "Seat");
    }


    public ExamInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ExamInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXAM_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"Course\" TEXT," + // 1: course
                "\"Time\" TEXT," + // 2: time
                "\"Classroom\" TEXT," + // 3: classroom
                "\"Seat\" TEXT);"); // 4: seat
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXAM_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExamInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(2, course);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String classroom = entity.getClassroom();
        if (classroom != null) {
            stmt.bindString(4, classroom);
        }
 
        String seat = entity.getSeat();
        if (seat != null) {
            stmt.bindString(5, seat);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExamInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(2, course);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String classroom = entity.getClassroom();
        if (classroom != null) {
            stmt.bindString(4, classroom);
        }
 
        String seat = entity.getSeat();
        if (seat != null) {
            stmt.bindString(5, seat);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExamInfo readEntity(Cursor cursor, int offset) {
        ExamInfo entity = new ExamInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // course
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // classroom
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // seat
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExamInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCourse(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setClassroom(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSeat(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExamInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExamInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExamInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
